config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :users
  resources :sessions, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'user', to: 'sessions#show'

  root 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
validates :user_id, presence: true
validates :points, numericality: { only_integer: true }

belongs_to :user
end

app/models/score_serializer.rb
class ScoreSerializer < RubySerializer::Base
  expose :points
  expose :rank
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true
  has_many :scores

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/user_serializer.rb
class UserSerializer < RubySerializer::Base
  expose :name
  expose :image
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  # protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all

    @leaderboard = RubySerializer.as_json @scores, include: :user

    render json: @leaderboard
  end

  # GET /scores/1
  # GET /scores/1.json
  def show

  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:points, :rank, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def show
    if current_user.nil?
      return
    else
      render json: current_user  
    end
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    @user_name = {}

    @users.each do |u|
      @total_points = 0
      u.scores.each do |s|
        @total_points += s.points
      end
      @user_name[u.name] = @total_points
    end

    # @users[1].scores[1].points

    render json: @user_name

  end

  # GET /users/1
  # GET /users/1.json
  def show
    render json: [@user, @user.scores]

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :about, :image, :score_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Simon">
  <head>
    <title>Simon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body ng-controller="ProfileController">
    <%= yield %>
    <script>
    var currentUser = <%= raw current_user.to_json %>
    var totalPoints = <%= raw @total_points.to_json %>
    </script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_for(score) do |f| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :points, in: 0..1000000 %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>
<br>
<%= link_to 'Home', root_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @score.points %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>

app/views/site/index.html.erb
<button class="testbtn">test</button>

<header class="fat-header" ng-hide="signedIn">simon</header>
<div class="navbar">
    <header ui-sref="ParentState.profile" >simon</header>
    <ul ng-show="signedIn">
        <li class="home" ui-sref-active="h-active" ui-sref="ParentState.profile">Home</li>
        <li class="game" ui-sref-active="g-active" ui-sref="ParentState.game">Game</li>
        <li class="leaderboard" ui-sref-active="l-active" ui-sref="ParentState.leaderboard">Leaderboard</li>
    </ul>
</div>
<div class="login-out">
  <% unless current_user %>
<div class="main-form-container is-flex">
  <h1>Welcome to Simon</h1>
  <img class="icon-md" src="/images/logo.png" alt="simon logo" />
    <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
  <% end %>
</div>

<div class="profile-user-left" >
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% end %>
</div>
</div>

<ui-view></ui-view>

app/views/users/_form.html.erb
<div class="main-form-container is-flex">
  <h1>Welcome to Simon</h1>
  <img class="icon-md" src="https://lh4.ggpht.com/qfy_9xdh28qHatRbeKmLI3Hne-cWktrT-zWojDGiByFWMrfF5oAx8qeNuj25EzwUdB4=w300" alt="twitter logo" />
  <h2>please create an account:</h2>

<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "name"%>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "email" %>
  </div>

  <div class="field" type="password">
    <%= f.label :password %>
    <%= f.text_field :password, placeholder: "password" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image, placeholder: "image url" %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about, placeholder: "quick blurb" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<!-- <h1>New User</h1> -->

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>